# Generated by Django 3.2.16 on 2023-02-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
