# Generated by Django 3.2.16 on 2023-02-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230128_1839'),
        ('posts', '0003_auto_20230201_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportofAbuse',
            new_name='AbuseReport',
        ),
    ]
