# Generated by Django 3.2.16 on 2023-01-23 12:28

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_followers', to='accounts.UserProfile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
