# Generated by Django 3.2.16 on 2023-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='{% static "images/profile_placeholder.jpg" %}', upload_to='profile_pics'),
        ),
    ]
